export const BLOG_ADDED = 'BLOG_ADDED';

export const CATEGORY_ADDED = 'CATEGORY_ADDED';

export const CATEGORY_FETCHED = 'CATEGORY_FETCHED';

export const CATEGORY_EDITED = 'CATEGORY_EDITED';

export const CATEGORY_DELETED = 'CATEGORY_DELETED';
